### ISSUE TITLE
multiplyOuterSparseLayer? where can I find it

### ISSUE THREAD

**Issue by s1162276945** [mesuvash/NNRec#1]
https://github.com/mesuvash/NNRec/blob/56f6a83982f2444b2238de703ae069d16b0b8cfc/nn/autorec/ae.py#L59

**Comment by mesuvash** [comment]
Its implemented in Cython. You can find it at https://github.com/mesuvash/NNRec/blob/master/nn/autorec/cython_matmul.pyx
