### ISSUE TITLE
best parameter settings?

### ISSUE THREAD

**Issue by stablum** [mesuvash/NNRec#3]
Hi,

I have been reading the AutoRec paper, which I found very interesting! I was wondering: what are the very best parameter settings that allowed to reach the reported good results? 

I was wondering which learning rate, which normalization coefficient and which bottleneck size has been used..

thanks in advance! :)
-Francesco

**Comment by mesuvash** [comment]
The optimal configuration for Movielens 1M dataset for I-Autorec is provided in https://github.com/mesuvash/NNRec/blob/master/nn/autorec/config/1M/1M.yaml

Let me know if that helps.

Cheers,
Suvash
